@startuml
left to right direction

actor "Secretaria" as secretaria
actor "Professor" as professor
actor "Aluno" as aluno
actor "Financeiro" as financeiro

rectangle "Sistema de Matrícula" {
    usecase "Realizar Matrícula" as UC1
    usecase "Cancelar Matrícula" as UC2
    usecase "Consultar Disciplinas" as UC3
    usecase "Consultar Alunos" as UC4
    usecase "Gerenciar Currículo" as UC5
    usecase "Gerenciar Disciplinas" as UC6
    usecase "Gerenciar Professores" as UC7
    usecase "Gerenciar Alunos" as UC8
    usecase "Notificar Cobrança" as UC9
}

rectangle "Sistema de Cobrança"{
    usecase "Cobrar \nMensalidade" as UC10
}

aluno --> UC1
aluno --> UC2
aluno --> UC3
UC1 ..> UC9 :<<include>>
professor --> UC4
secretaria --> UC5
secretaria --> UC6
secretaria --> UC7
secretaria --> UC8
UC10 .up.> UC9 :<<include>>
financeiro -up-> UC10
@enduml
